# Тут мы прописываем конфигурацию нашей сети
version: '3'

services:
  # Один сервис - сервер
  server:
    build:
      # Откуда будет брать image, или будет билдить 
      context: .
    # Передаем порт: т.е. будет транслировать с порта 8080 контейнера
    # на порт 8080 хоста
    # (хост):(контейнер)
    ports:
      - '8080:8080'
    environment:
      - PORT=8080